// Tous les visuels de l'app (personnages, icônes 3D, fonds, logo). Référencés via IMG.xxx
export const IMG = {
  logo: require('../assets/images/logo/fylio_logo.png'),
  logoF: require('../assets/images/logo/logo_f.png'),
  bg: {
    1: require('../assets/images/backgrounds/nebula1.jpg'),
    2: require('../assets/images/backgrounds/nebula2.jpg'),
    3: require('../assets/images/backgrounds/nebula3.jpg'),
    4: require('../assets/images/backgrounds/nebula4.jpg'),
  } as Record<1 | 2 | 3 | 4, any>,
  avatars: [
    require('../assets/images/characters/avatar_1.png'),
    require('../assets/images/characters/avatar_2.png'),
    require('../assets/images/characters/avatar_3.png'),
    require('../assets/images/characters/avatar_4.png'),
    require('../assets/images/characters/avatar_5.png'),
    require('../assets/images/characters/avatar_6.png'),
  ],
  mascotMain: require('../assets/images/characters/mascot_main.png'),
  filesMascot: require('../assets/images/characters/files_mascot.png'),
  galleryMascot: require('../assets/images/characters/gallery_mascot_right.png'),
  galleryMascotL: require('../assets/images/characters/gallery_mascot_left.png'),
  musicMascot: require('../assets/images/characters/music_mascot.png'),
  qrMascot: require('../assets/images/characters/qr_mascot.png'),
  transferHero: require('../assets/images/characters/transfer_hero.png'),
  // 11 frames du personnage qui avance avec la progression
  anim: [
    require('../assets/images/transfer/anim_1.png'), require('../assets/images/transfer/anim_2.png'),
    require('../assets/images/transfer/anim_3.png'), require('../assets/images/transfer/anim_4.png'),
    require('../assets/images/transfer/anim_5.png'), require('../assets/images/transfer/anim_6.png'),
    require('../assets/images/transfer/anim_7.png'), require('../assets/images/transfer/anim_8.png'),
    require('../assets/images/transfer/anim_9.png'), require('../assets/images/transfer/anim_10.png'),
    require('../assets/images/transfer/anim_11.png'),
  ],
  dev: {
    pc: require('../assets/images/icons/dev_pc.png'),
    android: require('../assets/images/icons/dev_android.png'),
    iphone: require('../assets/images/icons/dev_iphone.png'),
  } as Record<string, any>,
  ico: {
    send: require('../assets/images/icons/ico_send.png'),
    receive: require('../assets/images/icons/ico_receive.png'),
    bell: require('../assets/images/icons/ico_bell.png'),
    folder: require('../assets/images/icons/ico_folder.png'),
    settings: require('../assets/images/icons/ico_settings.png'),
    planet: require('../assets/images/icons/ico_planet_bulb.png'),
    tablet: require('../assets/images/icons/ico_tablet.png'),
    play: require('../assets/images/icons/ico_play.png'),
    pause: require('../assets/images/icons/ico_pause.png'),
  },
  emptyDevices: require('../assets/images/illustrations/empty_devices.png'),
  emptyHistory: require('../assets/images/illustrations/empty_history.png'),
  musicPlaylist: require('../assets/images/illustrations/music_playlist.png'),
  musicWidget: require('../assets/images/illustrations/music_widget_a.png'),
};